package org.shipkit.internal.gradle.java.tasks;

import org.gradle.api.artifacts.*;
import org.json.simple.JsonArray;
import org.json.simple.JsonObject;
import org.json.simple.Jsoner;
import org.shipkit.internal.notes.util.IOUtil;

import java.io.File;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Set;

public class CreateDependencyInfoFile {

    private static final String DESCRIPTION = "This file was generated by Shipkit Gradle plugin. See http://shipkit.org\n\n";

    public void createDependencyInfoFile(CreateDependencyInfoFileTask task) {
        JsonObject result = createJsonObject();
        result.put("description", DESCRIPTION);

        JsonArray dependencies = createJsonArray();

        for (Dependency dependency: task.getConfiguration().getAllDependencies()) {
            if (dependency instanceof ModuleDependency && !isSiblingDependency(task, dependency)) {
                addResolvedDependency(dependencies, (ModuleDependency) dependency);
            }
        }

        result.put("dependencies", dependencies);

        IOUtil.writeFile(task.getOutputFile(), Jsoner.prettyPrint(result.toJson()));
    }

    private void addResolvedDependency(JsonArray dependencies, ModuleDependency dependency) {
        if (!dependency.getArtifacts().isEmpty()) {
            for (DependencyArtifact artifact : dependency.getArtifacts()) {
                dependencies.add(getDependencyForSingleArtifact(dependency, artifact));
            }
        } else {
            dependencies.add(getDependencyForSingleArtifact(dependency, null));
        }
    }

    private boolean isSiblingDependency(CreateDependencyInfoFileTask task, Dependency dependency) {
        return task.getProjectGroup().equals(dependency.getGroup())
            && task.getCurrentProjectVersion().equals(dependency.getVersion());
    }

    private JsonObject getDependencyForSingleArtifact(ModuleDependency dependency, DependencyArtifact artifact) {
        JsonObject result = createJsonObject();

        result.put("dependencyGroup", dependency.getGroup());
        result.put("dependencyName", dependency.getName());
        result.put("dependencyVersion", dependency.getVersion());

        if (artifact != null) {
            result.put("artifactName", artifact.getName());
            result.put("artifactClassifier", artifact.getClassifier());
            result.put("artifactExtension", artifact.getExtension());
            result.put("artifactType", artifact.getType());
        }

        return result;
    }

    private JsonObject createJsonObject() {
        return new JsonObject(new LinkedHashMap<String, Object>()); // linkedHashMap to keep the order
    }

    private JsonArray createJsonArray() {
        return new JsonArray(new ArrayList<Object>()); //arrayList to keep the order
    }


}
