import org.mockito.releasetools.example.SomeApi;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library implements SomeApi {
    public boolean someLibraryMethod() {
        return true;
    }
}
