package org.shipkit.internal.gradle.java.tasks

import org.gradle.testfixtures.ProjectBuilder
import testutil.PluginSpecification

class CreateDependencyInfoFileTest extends PluginSpecification {

    CreateDependencyInfoFile createDependencyInfoFile = new CreateDependencyInfoFile()

    def "should create correct output file"() {
        given:

        def child = new ProjectBuilder().withName("child").withParent(project).build()
        child.group = "projGroup"
        def sibling = new ProjectBuilder().withName("sibling").withParent(project).build()
        sibling.version = "1.2.3"
        sibling.group = "projGroup"

        child.repositories.jcenter()
        child.configurations.create("runtime")
        child.dependencies {
            runtime child.project(":sibling")
            runtime "junit:junit:4.10"
            runtime "org.mockito:mockito-core:2.10.0:sources"
            runtime "org.mockito:mockito-core:2.10.0"
        }

        def runtimeConf = child.configurations.getByName("runtime")

        def output = tmp.newFile("output")
        def createDependencyInfoFileTask = project.tasks.create("createTask", CreateDependencyInfoFileTask) {
            outputFile = output
            configuration = runtimeConf
        }

        when:
        createDependencyInfoFile.createDependencyInfoFile(createDependencyInfoFileTask)

        then:
        output.text == """{
\t"description":"This file was generated by Shipkit Gradle plugin. See http:\\/\\/shipkit.org.",
\t"dependencies":[
\t\t{
\t\t\t"artifact":{
\t\t\t\t"extension":null,
\t\t\t\t"name":null,
\t\t\t\t"classifier":null,
\t\t\t\t"type":null
\t\t\t},
\t\t\t"name":"sibling",
\t\t\t"version":"1.2.3",
\t\t\t"group":"projGroup"
\t\t},
\t\t{
\t\t\t"artifact":{
\t\t\t\t"extension":null,
\t\t\t\t"name":null,
\t\t\t\t"classifier":null,
\t\t\t\t"type":null
\t\t\t},
\t\t\t"name":"junit",
\t\t\t"version":"4.10",
\t\t\t"group":"junit"
\t\t},
\t\t{
\t\t\t"artifact":{
\t\t\t\t"extension":"jar",
\t\t\t\t"name":"mockito-core",
\t\t\t\t"classifier":"sources",
\t\t\t\t"type":"jar"
\t\t\t},
\t\t\t"name":"mockito-core",
\t\t\t"version":"2.10.0",
\t\t\t"group":"org.mockito"
\t\t},
\t\t{
\t\t\t"artifact":{
\t\t\t\t"extension":null,
\t\t\t\t"name":null,
\t\t\t\t"classifier":null,
\t\t\t\t"type":null
\t\t\t},
\t\t\t"name":"mockito-core",
\t\t\t"version":"2.10.0",
\t\t\t"group":"org.mockito"
\t\t}
\t]
}"""
    }
}
