package org.shipkit.internal.notes.about;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

class CounterExtractor {

    public final static Pattern NUMBER_PATTERN = Pattern.compile("\\d+");
    public final static Pattern ABOUT_INFO_PATTERN =
            Pattern.compile(".*<sup><sup>\\*This release notes was automatically generated by \\[shipkit\\]\\(http://shipkit.org/\\) \\d+ times.\\*</sup></sup>.*\\s*");

    int getCounter(String firstLine) {
        if (firstLine.matches(ABOUT_INFO_PATTERN.pattern())) {
            String counter = getNumberFromMatchedLine(firstLine);
            return Integer.valueOf(counter);
        }
        return 0;
    }

    private String getNumberFromMatchedLine(String firstLine) {
        Matcher matcher = NUMBER_PATTERN.matcher(firstLine);
        matcher.find();
        return matcher.group();
    }
}
