package org.shipkit.internal.notes.about;

import java.io.File;

public class InformationAboutProvider {

    public static final String INFORMATION_ABOUT = "%s<sup><sup>*This release notes was automatically generated by [shipkit](http://shipkit.org/) %d times.*</sup></sup>%s\n\n";
    private static final String COMMENT_START = "<!---";
    private static final String COMMENT_END = "--->";

    private final ReleaseNoteCounter releaseNoteCounter = new ReleaseNoteCounter();

    public String getInformationAboutText(File releaseNoteFile, boolean informationAboutEnabled) {
        int nextReleaseNoteNumber = releaseNoteCounter.getNextReleaseNoteNumber(releaseNoteFile);
        if (informationAboutEnabled) {
            return InformationAboutProvider.getInformationAbout(nextReleaseNoteNumber);
        }
        return InformationAboutProvider.getCommentedInformationAbout(nextReleaseNoteNumber);
    }

    public static String getInformationAbout(int nextReleaseNoteNumber) {
        return String.format(INFORMATION_ABOUT, "", nextReleaseNoteNumber, "");
    }

    public static String getCommentedInformationAbout(int nextReleaseNoteNumber) {
        return String.format(INFORMATION_ABOUT, COMMENT_START, nextReleaseNoteNumber, COMMENT_END);
    }
}
